name: _error
timestamp: 1589335622
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1589312938
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-3125: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-4694: Menu
  messages:
    system-messages-2170: 'System Messages'
  content:
    system-content-3993: 'Page Content'
  copyright:
    copyright-2439: Copyright
  spacer:
    spacer-9173: Spacer
  branding:
    branding-1215: Branding
  mobile-menu:
    mobile-menu-2851: Mobile-menu
inherit: {  }
