version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _offline
  timestamp: 1468253830
layout:
  navigation:
    -
      - 'logo-9608 15'
      - 'spacer-6015 65'
      - 'social-3171 20'
  header:
    -
      - custom-7185
  /intro/: {  }
  /features/: {  }
  /utility/: {  }
  /above/: {  }
  /testimonials/: {  }
  /expanded/: {  }
  /container-main/:
    -
      -
        'mainbar 75':
          -
            - system-content-3997
          -
            - system-messages-9096
      -
        'sidebar 25': {  }
  footer:
    -
      - 'logo-9571 10'
      - 'copyright-1736 30'
      - 'spacer-8094 45'
      - 'totop-8670 15'
  /offcanvas/: {  }
structure:
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
  header:
    inherit:
      outline: default
      include:
        - attributes
  intro:
    type: section
    attributes:
      boxed: ''
  features:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  mainbar:
    type: section
    subtype: main
    inherit:
      outline: default
      include:
        - block
        - attributes
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
  offcanvas:
    attributes:
      boxed: ''
content:
  logo-9608:
    title: 'Logo / Image'
    inherit:
      outline: default
      particle: logo-9608
      include:
        - attributes
        - block
  social-3171:
    inherit:
      outline: default
      particle: social-3171
      include:
        - attributes
        - block
  custom-7185:
    title: 'Custom HTML'
    attributes:
      html: "<h2 class=\"g-title\">Offline</h2>\n<p>Sorry, We are Down for Maintenance.</p>"
  system-content-3997:
    inherit:
      outline: default
      particle: system-content-1587
      include:
        - attributes
        - block
  logo-9571:
    title: 'Logo / Image'
    inherit:
      outline: default
      particle: logo-9571
      include:
        - attributes
        - block
  copyright-1736:
    inherit:
      outline: default
      particle: copyright-1736
      include:
        - attributes
        - block
  totop-8670:
    title: 'To Top'
    inherit:
      outline: default
      particle: totop-8670
      include:
        - attributes
        - block
