version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1589312938
layout:
  /header/:
    -
      - 'logo-9674 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-2578
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-1604
    -
      - system-content-3389
  /footer/:
    -
      - position-footer
    -
      - 'copyright-2310 40'
      - 'spacer-3450 30'
      - 'branding-7632 30'
  offcanvas:
    -
      - mobile-menu-5691
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
