name: _body_only
timestamp: 1589335622
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1589312938
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-2712: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-8464: Menu
  messages:
    system-messages-8550: 'System Messages'
  content:
    system-content-9878: 'Page Content'
  copyright:
    copyright-1142: Copyright
  spacer:
    spacer-7810: Spacer
  branding:
    branding-6342: Branding
  mobile-menu:
    mobile-menu-6699: Mobile-menu
inherit: {  }
