version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1589312938
layout:
  /header/:
    -
      - 'logo-2712 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-8464
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-8550
    -
      - system-content-9878
  /footer/:
    -
      - position-footer
    -
      - 'copyright-1142 40'
      - 'spacer-7810 30'
      - 'branding-6342 30'
  offcanvas:
    -
      - mobile-menu-6699
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
