name: home
timestamp: 1589312949
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1589312938
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  showcase: Showcase
  feature: Feature
  subfeature: Subfeature
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  menu:
    menu-7077: Menu
  sample:
    sample-1: 'Gantry 5'
    sample-2: 'Getting Started'
    sample-3: 'Key Features'
  messages:
    system-messages-7884: 'System Messages'
  position:
    position-footer: Footer
  copyright:
    copyright-4982: Copyright
  social:
    social-4529: Social
  branding:
    branding-2272: Branding
  mobile-menu:
    mobile-menu-2906: 'Mobile Menu'
inherit: {  }
