name: home
timestamp: 1589926600
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1588258328
positions:
  aside: Aside
  sidebar: Sidebar
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-5507: 'System Messages'
  logo:
    logo-2624: 'Logo / Image'
    logo-8329: 'Logo / Image'
  menu:
    menu-6646: Menu
  social:
    social-5780: Social
  owlcarousel:
    owlcarousel-1279: 'Owl Carousel'
  owlcarousel_spiro:
    owlcarousel_spiro-5497: 'Owl Carousel - Spiro'
  custom:
    custom-3635: 'Custom HTML'
  spiro-card:
    spiro-card-4220: 'Spiro Card'
    spiro-card-8148: 'Spiro Card'
    spiro-card-2274: 'Spiro Card'
  custom-onpic:
    custom-onpic-8746: 'Custom HTML on Picture'
    custom-onpic-4671: 'Custom HTML on Picture'
    custom-onpic-2105: 'Custom HTML on Picture'
    custom-onpic-4462: 'Custom HTML on Picture'
  position:
    position-position-9572: Aside
    position-position-5850: Sidebar
  content:
    system-content-5698: 'Page Content'
  testimonial_owlcarousel:
    testimonial_owlcarousel-6773: 'Testimonials (owlcarousel)'
  spiro_picblock:
    spiro_picblock-3555: 'Spiro Picture Block'
    spiro_picblock-1252: 'Spiro Picture Block'
    spiro_picblock-6659: 'Spiro Picture Block'
    spiro_picblock-7264: 'Spiro Picture Block'
  copyright:
    copyright-8351: Copyright
  horizontalmenu:
    horizontalmenu-6115: 'Horizontal Menu'
  totop:
    totop-2097: 'To Top'
  mobile-menu:
    mobile-menu-5343: Mobile-menu
inherit:
  default:
    navigation: navigation
    system-messages-5507: system-messages-7972
    logo-2624: logo-9608
    menu-6646: menu-6409
    social-5780: social-3171
    above: above
    aside: aside
    position-position-9572: position-position-4734
    mainbar: mainbar
    system-content-5698: system-content-1587
    sidebar: sidebar
    position-position-5850: position-position-3949
    footer: footer
    logo-8329: logo-9571
    copyright-8351: copyright-1736
    horizontalmenu-6115: horizontalmenu-9034
    totop-2097: totop-8670
    offcanvas: offcanvas
    mobile-menu-5343: mobile-menu-5697
