name: _offline
timestamp: 1589312949
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1589312938
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-2968: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-9685: Menu
  messages:
    system-messages-3107: 'System Messages'
  content:
    system-content-7180: 'Page Content'
  copyright:
    copyright-3397: Copyright
  spacer:
    spacer-9492: Spacer
  branding:
    branding-1012: Branding
  mobile-menu:
    mobile-menu-9881: Mobile-menu
inherit: {  }
