version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1589312938
layout:
  /header/:
    -
      - 'logo-2968 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-9685
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-3107
    -
      - system-content-7180
  /footer/:
    -
      - position-footer
    -
      - 'copyright-3397 40'
      - 'spacer-9492 30'
      - 'branding-1012 30'
  offcanvas:
    -
      - mobile-menu-9881
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
